version: '3'

services:
  web_api:
    build: .
    container_name: "web-api-container"
    ports:
      - 8000:8000
    # volumes:
    #   - ./app/:/app
  redis:
    image: redis:7.2.0
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data:rw
    ports:
      - 6379:6379
    
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    restart: always
    ports:
      - 1883:1883 #default MQTT port
      # - 9001:9001 #default MQTT port for websockets
    volumes:
      - ./mqtt5/config:/mosquitto/config
      # - ./mqtt5/config/mosquitto.conf:/mosquitto.conf     
      - ./mqtt5/data:/mosquitto/data
      - ./mqtt5/log:/mosquitto/log


volumes:
  redis_volume_data:
  config:
  data:
  log:

networks:
  default:
