version: '3'

services:
  web_api:
    build: .
    container_name: "web-api-container"
    command: sh -c "uvicorn app:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
  redis:
    image: redis:7.2.0
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mqtt5:
    image: eclipse-mosquitto:1.6.15
    container_name: mqtt5
    restart: always
    ports:
      - 1883:1883 #default MQTT port
      - 9001:9001 #default MQTT port for websockets
